### ISSUE TITLE
Generate errors with Nuxt

### ISSUE THREAD

**Issue by Mikaleb** [johnbillion/wp-types#10] opened 2021-02-27 22:40 UTC
Might be a specific version of Typescript used with Nuxt, but AFAIK : 

``` json
 ERROR in node_modules/wp-types/index.ts:1007:5                                                                                                                                                                         23:35:04
TS2411: Property '"24"' of type 'string | undefined' is not assignable to string index type 'string'.
    1005 |      * Avatar URL with image size of 24 pixels.
    1006 |      */
  > 1007 |     "24"?: string;
         |     ^^^^
    1008 |     /**
    1009 |      * Avatar URL with image size of 48 pixels.
    1010 |      */

ERROR in node_modules/wp-types/index.ts:1011:5
TS2411: Property '"48"' of type 'string | undefined' is not assignable to string index type 'string'.
    1009 |      * Avatar URL with image size of 48 pixels.
    1010 |      */
  > 1011 |     "48"?: string;
         |     ^^^^
    1012 |     /**
    1013 |      * Avatar URL with image size of 96 pixels.
    1014 |      */

ERROR in node_modules/wp-types/index.ts:1015:5
TS2411: Property '"96"' of type 'string | undefined' is not assignable to string index type 'string'.
    1013 |      * Avatar URL with image size of 96 pixels.
    1014 |      */
  > 1015 |     "96"?: string;
         |     ^^^^
    1016 |     /**
    1017 |      * Avatar URL with image of another size.
    1018 |      */

ERROR in node_modules/wp-types/index.ts:1041:5
TS2411: Property 'up' of type 'unknown[] | undefined' is not assignable to string index type 'unknown[]'.
    1039 |      * The associated post.
    1040 |      */
  > 1041 |     up?: unknown[];
         |     ^^
    1042 |     [k: string]: unknown[];
    1043 |   };
    1044 |   [k: string]: unknown;

ERROR in node_modules/wp-types/index.ts:1232:5
TS2411: Property 'replies' of type 'unknown[] | undefined' is not assignable to string index type 'unknown[]'.
    1230 |      * The replies to the post (comments, pingbacks, trackbacks).
    1231 |      */
  > 1232 |     replies?: unknown[];
         |     ^^^^^^^
    1233 |     /**
    1234 |      * The taxonomy terms for the post.
    1235 |      */

ERROR in node_modules/wp-types/index.ts:1236:5
TS2411: Property '"wp:term"' of type 'unknown[] | undefined' is not assignable to string index type 'unknown[]'.
    1234 |      * The taxonomy terms for the post.
    1235 |      */
  > 1236 |     "wp:term"?: unknown[];
         |     ^^^^^^^^^
    1237 |     /**
    1238 |      * The featured image post.
    1239 |      */

ERROR in node_modules/wp-types/index.ts:1240:5
TS2411: Property '"wp:featuredmedia"' of type 'unknown[] | undefined' is not assignable to string index type 'unknown[]'.
    1238 |      * The featured image post.
    1239 |      */
  > 1240 |     "wp:featuredmedia"?: unknown[];
         |     ^^^^^^^^^^^^^^^^^^
    1241 |     /**
    1242 |      * The parent post.
    1243 |      */

ERROR in node_modules/wp-types/index.ts:1244:5
TS2411: Property 'up' of type 'unknown[] | undefined' is not assignable to string index type 'unknown[]'.
    1242 |      * The parent post.
    1243 |      */
  > 1244 |     up?: unknown[];
         |     ^^
    1245 |     [k: string]: unknown[];
    1246 |   };
    1247 |   [k: string]: unknown;

ERROR in node_modules/wp-types/index.ts:1411:5
TS2411: Property '"wp:featuredmedia"' of type 'unknown[] | undefined' is not assignable to string index type 'unknown[]'.
    1409 |      * The featured image post.
    1410 |      */
  > 1411 |     "wp:featuredmedia"?: unknown[];
         |     ^^^^^^^^^^^^^^^^^^
    1412 |     [k: string]: unknown[];
    1413 |   };
    1414 |   [k: string]: unknown;
```

**Comment by johnbillion** [comment] 2021-02-28 09:53
Thanks for the report! Can you let me know how to reproduce the error please? package.json, Typescript config, etc.

**Comment by Mikaleb** [comment] 2021-02-28 17:09
Hi, here is my package.json : 

``` json
{
  "name": "influlab",
  "version": "1.0.0",
  "private": true,
  "typings": "types/index.d.ts",
  "files": [
    "./types/index.d.ts"
  ],
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest"
  },
  "dependencies": {
    "@mdi/font": "^5.9.55",
    "@nuxt/content": "^1.13.1",
    "@nuxt/utils-edge": "^2.15.1-26892035.d58c4f72",
    "@nuxtjs/axios": "^5.13.1",
    "@nuxtjs/composition-api": "^0.20.1",
    "@nuxtjs/proxy": "^2.1.0",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/sentry": "^5.0.2",
    "@types/lodash": "^4.14.168",
    "core-js": "^3.9.0",
    "date-fns": "^2.17.0",
    "js-cookie": "^2.2.1",
    "lodash": "^4.17.21",
    "nuxt": "^2.15.2",
    "nuxt-build-optimisations": "^1.0.1",
    "nuxt-i18n": "^6.20.3",
    "simple-icons": "^4.12.0",
    "vee-validate": "^3.4.5",
    "vue-social-sharing": "^3.0.5",
    "wp-nuxt": "^1.0.28",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@nuxt/types": "^2.15.2",
    "@nuxt/typescript-build": "^2.0.6",
    "@nuxtjs/color-mode": "^2.0.3",
    "@nuxtjs/google-fonts": "^1.2.0",
    "@nuxtjs/tailwindcss": "^3.4.2",
    "@sentry/typescript": "^5.20.1",
    "@types/zxcvbn": "^4.4.0",
    "@vue/test-utils": "^1.1.3",
    "autoprefixer": "^9",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "jest": "^26.6.3",
    "node-sass": "^5.0.0",
    "nuxt-purgecss": "^1.0.0",
    "postcss": "^7",
    "prettier": "^2.2.1",
    "sass-loader": "10.1.1",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat@2.0.3",
    "tailwindcss-dark-mode": "^1.1.7",
    "ts-jest": "^26.5.2",
    "vue-jest": "^3.0.7",
    "wp-types": "^1.8.1"
  }
}

```

Tsconfig : 


```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "DOM"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "baseUrl": ".",
    "outDir": "dist",
    "paths": {
      "~/*": ["./src/*"],
      "@/*": ["./src/*"],
      "~~/*": ["./*"],
      "@@/*": ["./*"]
    },
    "types": [
      "@nuxt/types",
      "@nuxt/content",
      "@types/node",
      "@nuxt/vue-app",
      "nuxt-i18n",
      "vee-validate",
    ],
    "skipLibCheck": true,
  },
  "exclude": [
    ".nuxt",
    ".vscode",
    "dist",
    "dist.js",
    "node_modules",
  ],
  "globals": {
    "it": false,
    "expect": false
  },
  "pretty": true,
  "allowSyntheticDefaultImports": true,
  "suppressImplicitAnyIndexErrors": true,
  "linterOptions": {
    "exclude": [
      "node_modules"
    ]
  }
}
```

**Comment by johnbillion** [comment] 2021-03-07 14:56
I'm going to close this off as a duplicate of https://github.com/johnbillion/wp-json-schemas/issues/29 as it appears to be the same problem. Cheers.

**Closed as completed by johnbillion** 2021-03-07 14:56 UTC
